### ISSUE TITLE
网页已拒接连接

### ISSUE THREAD

**Issue by Littlechickencub** [pete-li/inpainting_edgeconnect#3]
你好，我22年6月份登陆过edge-connect图像修复系统，当时是出现涂抹掩模之后点击无法点击修复按钮，就没看了，最近想仔细研究一个这个系统，但是代码运行之后，进入网页显示127.0.0.1 已拒绝连接，不知道是什么问题，我尝试注释过注释setting.py文件中的'django.middleware.clickjacking.XFrameOptionsMiddleware'，重启项目没用，刚开始用Django，有各种各样的问题，麻烦赐教，谢谢

**Comment by pete-li** [comment]
你好，我已经很久没碰django啦，这个是毕业设计的时候做的，我觉得应该是django配置有问题，你可以看下django相关的bug搜索试试看，用下谷歌搜索别用百度。
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pete-li/inpainting_edgeconnect"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月8日(星期三) 晚上6:32
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[pete-li/inpainting_edgeconnect] 网页已拒接连接 (Issue #3)





 
你好，我22年6月份登陆过edge-connect图像修复系统，当时是出现涂抹掩模之后点击无法点击修复按钮，就没看了，最近想仔细研究一个这个系统，但是代码运行之后，进入网页显示127.0.0.1 已拒绝连接，不知道是什么问题，我尝试注释过注释setting.py文件中的'django.middleware.clickjacking.XFrameOptionsMiddleware'，重启项目没用，刚开始用Django，有各种各样的问题，麻烦赐教，谢谢
